### ISSUE TITLE
Splash Page

### ISSUE THREAD

**Issue by rsmease** [rsmease/ashai#11]
- [x] Authenticated / protected routes
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation

**Comment by rsmease** [comment]
Stephen, I should have tagged you on this one during our auth phase. Nothing has changed. Let me know if you see issues.

**Comment by s-pangburn** [comment]
- [x] It definitely looked better when everything was in the center :)

**Comment by rsmease** [comment]
@s-pangburn This is now fixed.

**Comment by s-pangburn** [comment]
👍
