### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by rsmease** [rsmease/ashai#5]
- [x] Backend: model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation

**Comment by rsmease** [comment]
@s-pangburn I am having one issue with this that I need help with. I can think of ways to fix it, I just don't know best practice. When you toggle between the teams on the sidebar, sometimes it doesn't remount so the team view page is blank. How can I make sure that it remounts every time you head to the link?

**Comment by rsmease** [comment]
If you click on a user image (the user's profile) between heading to team page A and team page B (so team -> user -> team), there are never issues, meaning that it's definitely a question of getting the team's view to reload it's data every time.

**Comment by s-pangburn** [comment]
I don't seem to get that error, so you might have fixed this already, but the solution is to use componentWillReceiveProps, which is a lifecycle method that activates every time a component is about to rerender. You would have a conditional statement that compares `this.props.location.pathname` to `nextProps.location.pathname`, or you would compare `this.props.match.params.id` to `nextProps.match.params.id`, the exact comparison doesn't matter, what you want to verify is that the component is remounting because of a url change, then you fetch the requisite data from the database and update the state.

**Comment by s-pangburn** [comment]
As for feedback, the team view is looking great! The splash images that appear on hover are especially impressive and overall aesthetically pleasing to look at.

- [x] I think it would enhance the team view's usability if the team member's splash image was a clickable link that took you to their task list.
- [x] In fact, I think the entire div should be clickable, not just "View Profile". "View Profile should highlight blue when any part of the div is hovered.
- [x] Similarly to projects, I should be able to create, edit, and delete teams, as well as add team members myself.

**Comment by rsmease** [comment]
@s-pangburn I now have all the CRUD actions available to teams in the sidebar. Hover over the items and you'll see the affordances. Note my comments on the projects issue regarding the two issues. They are issues for teams, too. 

I will have a fix on the splash images issue by tomorrow morning, I'm just procrastinating because I'm not sure how I want to handle the design.

**Comment by rsmease** [comment]
- [x] Edit changes / New teams do not populate in the sidebar after updating/creating; I have to rerender the page with a refresh and then they're visible. this.forceUpdate() didn't seem to work.
- [x] When deleting a team, I'm not redirected to '/app', so the empty team page with the deleted data is still available. I would image that I should fix this by adding a .then(history.push("home")) chained to requestToDeleteTeam() call. Is this the best approach?

**Comment by s-pangburn** [comment]
- [x] CRUD affordances should `cursor: pointer` on hover
- [x] Modal should close when you click outside of it

**Comment by s-pangburn** [comment]
Check the Projects issue for my notes on the problems you are having!

**Comment by rsmease** [comment]
@s-pangburn I think we should be good to go, although I think there's a lack of affordance on one thing: when you hover over a profile on the Team show page, you can click anywhere on the hover card to go to that person's show page, but I'm not sure how to express that. I don't want to ruin the card by shoving a 'Click Anywhere To View Profile' banner in the card. It hides too much of the person's face. What do you think I should do?

**Comment by rsmease** [comment]
@s-pangburn Final changes are live on Heroku. http://www.ashai.co

**Comment by s-pangburn** [comment]
`cursor: pointer` is more than enough for that. It's an unconscious psychological trigger, so you don't need to worry about people not picking up on it :)

If you're really worried though, you can change the green "bio" text on the photos to "click to view profile", but I don't think that's actually necessary, imo.

**Comment by s-pangburn** [comment]
In any case, this looks good! Great work 👍
