### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by rsmease** [rsmease/ashai#7]
- [x] Presentational Components 
- [x] Styling (modal)
- [x] Smooth, bug-free navigation

**Comment by rsmease** [comment]
@s-pangburn This is now ready for review. User profile can be edited via top right of home page.
http://www.ashai.co

**Comment by s-pangburn** [comment]
CSS bug:
![screen shot 2017-12-01 at 1 46 12 pm](https://user-images.githubusercontent.com/8031316/33504867-06f964ce-d69e-11e7-9ef4-ac519fe85a12.png)

**Comment by rsmease** [comment]
Weird. Ok. I'm on it.

**Comment by rsmease** [comment]
@s-pangburn Can you confirm that you're seeing that bug on either IE (kidding) or Firefox? I cannot recreate it using Chrome or Safari.

**Comment by s-pangburn** [comment]
Chrome, actually, haha

**Comment by rsmease** [comment]
@s-pangburn This was a fun midnight hour challenge. Everything is fixed. The css bug and the changes-to-state bug! Now turning to production polishing and README.
